### ISSUE TITLE
Breaking change in graphql-core

### ISSUE THREAD

**Issue by NathanDeMaria** [graphql-python/gql#51] opened 2019-12-02 17:30 UTC
There's some backward-compatibility breaks in `graphql-core==3.0.0`, that lead to the following import error:

```python
from gql import Client
```

```traceback
ImportError                               Traceback (most recent call last)
<ipython-input-1-2d34726b19bf> in <module>
----> 1 from gql import Client

~\AppData\Local\Continuum\miniconda3\lib\site-packages\gql\__init__.py in <module>
      1 from .gql import gql
----> 2 from .client import Client
      3
      4 __all__ = ['gql', 'Client']

~\AppData\Local\Continuum\miniconda3\lib\site-packages\gql\client.py in <module>
      1 import logging
      2
----> 3 from graphql import parse, introspection_query, build_ast_schema, build_client_schema
      4 from graphql.validation import validate
      5

ImportError: cannot import name 'introspection_query' from 'graphql' (C:\Users\nathan.demaria\AppData\Local\Continuum\miniconda3\lib\site-packages\graphql\__init__.py)
```

AFAIK the solution here is add a ceiling `graphql-core<3.0.0` to the `install_requires` of this package, but I'm curious if somebody familiar with the plan for packages in this repo has better options/longer term recommendations - I see repos for `graphql-core-next` and `gql-next`, and it looks like the `graphql-core` package is now published to PyPI from the `-next` repo, but `gql` is still from this repo.

**Comment by Cito** [comment] 2019-12-02 20:27
Actually, graphql-core 3.0.0 should be compatible to GraphQL.js 14 and still have introspection_query (see graphql-python/graphql-core-next#69). I will fix that in 3.0.1. However, this is not a permanent fix and will break again, once we release a version compatible with GraphQL.js 15, and maybe other things are also broken with `graphql-core>=3.0.0`.

So your suggestion to require `graphql-core<3.0.0` in setup.py and creating a new release with that restriction (maybe called 2.0) is the proper solution. Then, a new release (maybe called 3.0) that supports graphql core 3 should be created.

**Comment by Cito** [comment] 2019-12-02 20:38
This is actually #47. The problem is that currently nobody feels responsible. We need more volunteers as maintainers to keep graphql-python alive.

**Comment by Cito** [comment] 2019-12-05 22:18
This is now fixed, but we need to push a patch release to PyPI. For this to happen, @syrusakbary to give somebody maintainer rights on PyPI.

**Comment by Cito** [comment] 2019-12-06 16:00
As a side note, graphql-core 3.0.1 is now compatible with graphql-js 14.5.8 again.

**Comment by dineshsriram** [comment] 2019-12-10 23:09
Thanks @Cito! 

@syrusakbary Can you help push out the patch release to PyPI?

**Comment by JonasVautherin** [comment] 2019-12-18 14:34
Is it planned to deploy a new release with this fix?

**Comment by Cito** [comment] 2019-12-29 20:56
Version 0.2.0 has now been released on PyPI.

**Closed by Cito** 2019-12-29 20:56 UTC
