### ISSUE TITLE
Phoenix transport: breaking early from async generator loop requires canceling receive_data_task

### ISSUE THREAD

**Issue by pzingg** [graphql-python/gql#225] opened 2021-08-10 02:20 UTC
I don't know if there is a Slack channel or other forum for the gql project, so I'm posing this here as an issue. I would like to see an example of a subscription that uses one of the async transports (such as PhoenixChannelWebsocketsTransport) for the use case below. It's something that I had working with gql 2.x, after adding my own (probably naive) implementation of Phoenix channels. The target server is Absinthe GraphQL.

The inputs for the process are:

* a mutation document and variables
* a subscription document and variables (subscription updates are triggered by the mutation)
* a coroutine (or asyncio task?) that can act on each subscription update received, as indicated below
* an optional timeout, after which the subscription will be ended

Then the process is:

1. Send a subscription request with the coroutine as a parameter.
2. If the subscription is successful, send a mutation request that will trigger subscription updates.
3. As each update arrives on the subscription (inside an async generator for loop), the coroutine acts on it (for example printing, or parsing the ExecutionResult and processing results). The coroutine may also, as it parses an update, decide to end the subscription if it decides that no more updates are expected, and return any data it wants.
4. If the timeout is exceeded, the process will unsubscribe, and return any results collected by the coroutine, as well as an indication that the process ended via a timeout.

It looks like the standard way a subscription is ended is when it receives a "complete" message on the websocket, but in my case I want the client to decide when to stop subscribing.

**Comment by pzingg** [comment] 2021-08-10 19:45
I was successful in developing a coroutine that subscribes to an Absinthe subscription, after struggling to find the correct channel name, "__absinthe__:control" to use when constructing the `PhoenixChannelWebsocketsTransport`. Using some of the test examples, I am almost there, except I don't know how to stop the subscription inside of an asynchronous generator loop.

Here's the code

```
async def subscribe_to_updates(doc, vars, ...):
    absinthe_control_transport = PhoenixChannelWebsocketsTransport(...)
    async with Client(transport=absinthe_control_transport) as session:
        generator = session.subscribe(doc, variable_values=vars)
        async for result in generator:
            data = result['updated']
            print(data)
            if data['phase'] in ['nophase', 'completed', 'canceled']:
                # want to exit coroutine, setting data as the result
                print('break')
                await generator.aclose() # is this necessary?
                return data 
    return None
```

The code does receive results and prints the data, but the `generator.aclose()` and `return` statements do not end the execution. Instead, the awaitable sits until a timeout of 10 seconds happens (not sure which of the websockets timeouts this is). Same thing happens if I raise an exception inside the for loop. If I raise an exception or return before the for loop, the coroutine exits immediately, although there is an assertion failure because the websocket connection has not yet been made.

**Comment by pzingg** [comment] 2021-08-11 00:02
I fixed the code by putting a `break`, not a `return` inside the loop, and making sure that the `return` is outside the `async with ... as session` block. The code is fairly close to the `test_websocket_subscription_break` in test\_websocket\_subscription.py and it does break immediately. However, I had to insert a call to cancel the transport's `receive_data_task`, followed by the `await session._generator.aclose()`. 

Works on Python 3.8.

```
async def subscribe_to_updates(doc, vars, ...):
    absinthe_control_transport = PhoenixChannelWebsocketsTransport(...)
    data = None
    async with Client(transport=absinthe_control_transport) as session:
        async for result in session.subscribe(doc, variable_values=vars):
            data = result['updated']
            if data['phase'] in ['completed', 'canceled']:
                # Here we want to exit coroutine, returning `data` as the result
                # Note: the following steps seem to be necessary
                # to avoid assertion failures and other exceptions
                print(f'cancelling receive_data_loop')
                session.transport.receive_data_task.cancel()
                print(f'closing generator')
                await session._generator.aclose()
                break

    return data
```

**Comment by leszekhanusz** [comment] 2021-08-11 00:07
`generator.aclose()` is not needed if you have a recent version of python (at least 3.7)

In theory, in order to exit a subscription, you can:
 - simply use `break`
 - use `return`
 - raise an exception
 - use `generator.aclose()`
 - or even [cancel the current task](https://gql.readthedocs.io/en/v3.0.0a6/advanced/async_advanced_usage.html)

In all these cases, gql should close the connection gracefully.

The `PhoenixChannelTransport` has not been tested in great detail and you could help us test it further.

Could you please try the PR #227 to see if it is better for you ?

If you could then retry with [logs set to DEBUG for the websockets code](https://gql.readthedocs.io/en/v3.0.0a6/advanced/logging.html) it would help debug the problems

**Comment by pzingg** [comment] 2021-08-11 00:15
Thanks, it was able to use the logging output to track this down. 

Here are my results on Python 3.8.10:

1. cancel receive_data_task and await generator.aclose: quick exit, no exceptions
2. only cancel receive_data_task (without await generator.aclose): waits for timeout in `_close_coro: starting clean_close`
3. only await generator.aclose (without cancel receive_data_task): ask exception was never retrieved. assertion failed in `"websockets.py", line 179, in _receive, assert self.websocket is not None`
4. break without either: waits for timeout as in case 2, also fails assertion in case 3.

**Comment by leszekhanusz** [comment] 2021-08-11 00:28
About the 10 seconds delay, we have 3 different timeout defined by default to 10 seconds:
- connect_timeout                                                                           
- close_timeout                                                                  
- ack_timeout

In your case, the problematic timeout seems to be the `close_timeout`
For confirmation, you can change the timer value in the transport init

**Comment by leszekhanusz** [comment] 2021-08-11 00:32
But please test the PR #227 with only a break, the assertion bug should disappear.

**Comment by pzingg** [comment] 2021-08-11 03:20
With PR #227 I could remove the `receive_data_task.cancel()` but still need to do the `await session._generator.aclose()` to avoid waiting. If I omit that, there is a 10 second timeout between these two log entries:

```
DEBUG:gql.transport.websockets:_close_coro: starting clean_close
...10 second pause here...
INFO:gql.transport.websockets:>>> {"topic": "__absinthe__:control", "event": "phx_leave", "payload": {}, "ref": 3}
```

**Comment by leszekhanusz** [comment] 2021-08-11 08:38
In the websockets transport, in the subscriptions protocol you need to send a "stop" message to close a subscription on the backend.
When the user wants to close the connection (not an exception or connection closed), we want to send a stop for each open subscription and wait for the complete message for all of them before sending the final message and closing the connection.

The `_no_more_listener` event is used to know when all the subscriptions generators have been been properly closed.

For the phoenix transport, there is apparently no "stop" message in the protocol. So the `_send_stop_message` will simulate receiving a "complete" message when we need to close the connection cleanly.

In theory, in that case, all the subscriptions generators still open will receive the "complete" answer or be already closed.
So in theory at some point, len(self.listeners) will be 0 and the `_no_more_listeners` event will be set.

Apparently this is not the case for you...
Could you reproduce your behavior in a test case ?

**Comment by pzingg** [comment] 2021-08-11 15:20
In the code that I had written to support Absinthe subscriptions with earlier versions of gql, I tore down the client subscription by sending an "unsubscribe" Phoenix Channel message over the websocket. This is part of the Absinthe protocol, and corresponds I guess to the "complete" type you use with vanilla Websockets.

Here is some pseudocode in the style of `_send_stop_message`. Do you want me to try and implement it in a fork of PR #227?

```
async def _send_unsubscribe_message(self, query_id: int) -> None:
        """Send an unsubscribe message to Absinthe for a listener's query_id.
        """
        query_id = self.next_query_id
        self.next_query_id += 1

        # TODO:
        # 1. add an attribute, self.join_ref, which is the saved value of query_id that was sent to Absinthe
        # as the "ref" item in the "phx_join" message when the channel was first joined.
        # 2. lookup the subscription_id that corresponds to the listener query_id in 
        # self.subscription_ids_to_query_ids. It is something like "__absinthe__:doc:-5764607...".
        unsubscribe_message = json.dumps(
            {
                "topic": self.channel_name, # This was "__absinthe__:control"
                "event": "unsubscribe",
                "payload": {"subscription_id": subscription_id},
                "ref": query_id,
                "join_ref": self.join_ref
            }
        )

        await self._send(unsubscribe_message)
```

**Comment by leszekhanusz** [comment] 2021-08-12 16:19
Could you just simulate the Absinthe answers like in the current tests? So that we don't need another dependency.

**Comment by pzingg** [comment] 2021-08-12 16:59
Will do.

**Closed** 2021-08-22 16:40 UTC
Labels: type: bug
