### ISSUE TITLE
Is it possible to silence logs?

### ISSUE THREAD

**Issue by alexisrolland** [graphql-python/gql#182] opened 2020-12-12 08:48 UTC
Hello and thank you for developing this GraphQL client!

I would like to know if there is an option to silence the logs? Or how could I mute them in general maybe using the default Python logging module?

Thank you

**Comment by leszekhanusz** [comment] 2020-12-12 11:03
Duplicate of #178

**Closed by leszekhanusz** 2020-12-12 11:03 UTC
Labels: type: duplicate
