### ISSUE TITLE
wrong import dependency version with new requests minor release 2.30.0

### ISSUE THREAD

**Issue by RiverWalker92** [graphql-python/gql#412] opened 2023-05-05 14:16 UTC
The new version of requests (2.30) has some breaking changes that prevent it working with requests-toolbelt <1.
It does work with version 1.0.0 of requests-toolbelt, so I suggest updating the setup.py requirements:
"requests_toolbelt>=0.9.1,<1", 
into 
"requests_toolbelt>=1.0.0",

I do not know if the new breaking changes affect any other parts of gql, so I am not directly putting in a merge request. Limiting requests to 2.29 is also a solution.

Kind regards and thanks for the nice library

**Comment by leszekhanusz** [comment] 2023-05-05 16:24
Thanks for your report.
Are you sure the problem is with `requests_toolbelt`?
I believe the problem with version 2.30 of `requests` is related to the fact that [requests 2.30 now bumped the urllib3 library version](https://github.com/psf/requests/issues/6443).

The tests which were passing before [are now failing](https://github.com/graphql-python/gql/actions/runs/4818995642/jobs/8740932288) (I tried to re-run all jobs on this previous test action on GitHub)

The proper solution should be I think to restrict urllib3 to < 2 for now.

**Comment by RiverWalker92** [comment] 2023-05-05 16:35
Ah ok, I didn't test any other parts of the library. But simple gql requests where working for me with the new requests-toolbelt version. It is true that the error came from urllib3. An import error of urllib3.contrib.appengine.

**Comment by leszekhanusz** [comment] 2023-05-05 16:54
I fixed it in PR #413 
Unfortunately I don't have the time to make a new version right now. It will have to wait for tomorrow.

**Comment by leszekhanusz** [comment] 2023-05-06 19:45
Fixed in [pre-release v3.5.0b4](https://github.com/graphql-python/gql/releases/tag/v3.5.0b4) and in [bugfix release 3.4.1](https://github.com/graphql-python/gql/releases/tag/v3.4.1).

**Closed by leszekhanusz** 2023-05-06 19:45 UTC
Labels: type: bug

**Comment by RiverWalker92** [comment] 2023-05-08 20:10
Thanks for the quick release, already using it at work now!
