### ISSUE TITLE
Results of subfields are somehow cached and not re-fetched when using subscriptions

### ISSUE THREAD

**Issue by maaft** [graphql-python/gql#128] opened 2020-08-06 16:12 UTC
When you have the following schema:
```
type Subscription {
   foo: Foo!
}

type Foo {
   bar: Bar!
}

type Bar {
   id: String!
}
```

and a following python subscription with python-gql:
```python
       query = gql('''
                    subscription foo {
                        foo {
                            bar {
                                id
                            }
                        }
                    }
                ''')

        ws_transport = WebsocketsTransport(
                url="ws://{}".format(self.address),
                headers={
                    "Content-type": "application/json",
                    "Authorization": "Bearer " + self.token
                },
            )

        async with Client(transport=ws_transport, fetch_schema_from_transport=True) as session:
            async for result in session.subscribe(query, variable_values=params):
               print(result)
```

When I change the `id` of my `bar` object and publish the updated `foo` object, my client is still displaying the old `id` of the `bar` object.

I would expect to display the correct updated id. Or is this expected behavior and should I directly subscribe to my `Bars` ?

**Comment by leszekhanusz** [comment] 2020-08-09 16:32
There is no caching in gql, I suspect that the problem is with your backend. By using a logging level of INFO, you can see the exchanged message to and from the backend and see if it is the case:

```python
import logging
logging.basicConfig(level=logging.INFO)
```

**Comment by leszekhanusz** [comment] 2020-09-07 19:58
I am closing this issue. Please reopen if you have more information.

**Closed by leszekhanusz** 2020-09-07 19:58 UTC
Labels: status: needs more information, type: question or discussion
